# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghtkn" do
  desc "Create GitHub App User Access Token for secure local development"
  homepage "https://github.com/suzuki-shunsuke/ghtkn"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghtkn"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.1.1/ghtkn_darwin_amd64.tar.gz"
      sha256 "c397ca31d5032e59393727b844ee682735c91b7288cbdaf5c0b8343c7a26ecb2"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.1.1/ghtkn_darwin_arm64.tar.gz"
      sha256 "20618b67e6e1b0a3d4df977d845075db801cd4cf006c6787256d4963f44a46f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.1.1/ghtkn_linux_amd64.tar.gz"
      sha256 "f4c3f056f812adfc56cc1a5ae7b6608e4e6b5a4fccab7f081916a06490231d1a"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v0.1.1/ghtkn_linux_arm64.tar.gz"
      sha256 "45c303425144292b43a90bc4e87f48d0b9fcca6325e8863cde25904e6355aaf0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghtkn"]
    end
  end

  # No zap stanza required
end
