# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghtkn" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "24d161c0dbd05d708854473e6df5b5532c364d311f6fa207750fcd10665002ef"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b34338604a822af0f80dbed5f37ec50e0078ae3295b2f1e2cb3c02d028f1231"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ad54702bdbf1623d7203023f6517a006904bfa208e935fb7012bd3df7d9bb2a"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5555b5f84acce0d0ac3806fa5379d0a10006865d790aad72c69ec809e9865db0"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_linux_arm64.tar.gz"
    end
  end

  name "ghtkn"
  desc "Create GitHub App User Access Token for secure local development"
  homepage "https://github.com/suzuki-shunsuke/ghtkn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghtkn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghtkn"]
    end
  end

  # No zap stanza required

end
