# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghtkn" do
  version "0.2.7"

  on_macos do
    on_intel do
      sha256 "6378cf136fba4a573bec24bd0e2a255f0da58b66623bd5ab631e80c3b89087e7"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03dbe1264bf559e7f4d2f5fb035562c0fc4483200906f0d656017d53ee26f0df"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aecec0f65e946b11f4ac61a2745845d1b658b989bf2d17da90968e51adf3f646"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfa41d024d450fa5e075d7a63581cb486fb5a8115bd08dcce51713112b599064"
      url "https://github.com/suzuki-shunsuke/ghtkn/releases/download/v#{version}/ghtkn_linux_arm64.tar.gz"
    end
  end

  name "ghtkn"
  desc "Create GitHub App User Access Token for secure local development"
  homepage "https://github.com/suzuki-shunsuke/ghtkn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghtkn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghtkn"]
    end
  end

  # No zap stanza required

end
